News/Models/DataBase/Appdbcontext.cs
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Data.Common;

namespace News.Models.DataBase
{
    public class Appdbcontext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=ARMAN\SQLEXPRESS;Database=News;Trusted_Connection=True;TrustServerCertificate=True;Integrated Security=True;");
            base.OnConfiguring(optionsBuilder);
        }
        public DbSet<User> Users { get; set; }
        public DbSet<Newses> News { get; set; }
            
    }
}

News/Models/Newses.cs
namespace News.Models
{
    public class Newses
    {
        public int Id { get; set; }
        public string Title { get; set; }  
        public string Text { get; set; }

    }
}

News/Models/Reporter.cs
namespace News.Models
{
    public class Reporter : User
    {
    }
}

News/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace News.Models
{
    public class User
    {
        public int Id { get; set; }

        [Required]
        public string UserName{ get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }
        public int Age { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public int Password { get; set; }
    }
}

News/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using News.Models;
using News.Models.DataBase;
using System.Diagnostics;

namespace News.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;      
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
           
            return View();
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignUp(User user)
        {
            if (ModelState.IsValid)
            {
               
                return RedirectToAction("SignUpSuccess");
            }

            return View(user);
        }

        public IActionResult SignUpSuccess()
        {
            return View();
        }
       
    }
}

News/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using News.Models;

namespace News.Controllers
{
    public class NewsController : Controller
    {
        private static List<Newses> news = new List<Newses>();

        public IActionResult index()
        {
            return View(news);
        }
        [HttpGet]
        public IActionResult Creat()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Creat(Newses model)
        {
            news.Add(model);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var Newsee = news.FirstOrDefault(w => w.Id == id);
            news.Remove(Newsee);
            return RedirectToAction("Index");

        }
        public IActionResult Detail(int id)
        {
            var Newsee = news.FirstOrDefault(x => x.Id == id);
            return View(Newsee);
        }

    }
}

News/Views/Home/SignUp.cshtml
@model User

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
<div class="container">
    <div class="card card-login mx-auto text-center bg-dark">
        <div class="card-header mx-auto bg-dark">
            <span> <img src="https://amar.vote/assets/img/amarVotebd.png" class="w-75" alt="Logo"> </span><br />
            <span class="logo_title mt-5"> Login Dashboard </span>
            <!--            <h1>--><?php //echo $message?><!--</h1>-->

        </div>
        <div class="card-body">
            <form action="" method="post">
                <div class="input-group form-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                    </div>
                    <input type="text" name="email" class="form-control" placeholder="Username" asp-for="UserName">
                </div>

                <div class="input-group form-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-key"></i></span>
                    </div>
                    <input type="password" name="password" class="form-control" placeholder="Password" asp-for="Password">
                </div>

                <div class="form-group">
                    <input type="submit" name="btn" value="Login" asp-controller="Home" asp-action="Index" class="btn btn-outline-danger float-right login_btn">
                </div>

            </form>
        </div>
    </div>
</div>
<style>
    body {
        background: white !important;
    }

    .card {
        border: 1px solid #28a745;
    }

    .card-login {
        margin-top: 130px;
        padding: 18px;
        max-width: 30rem;
    }

    .card-header {
        color: #fff;
        /*background: #ff0000;*/
        font-family: sans-serif;
        font-size: 20px;
        font-weight: 600 !important;
        margin-top: 10px;
        border-bottom: 0;
    }

    .input-group-prepend span {
        width: 50px;
        background-color: #ff0000;
        color: #fff;
        border: 0 !important;
    }

    input:focus {
        outline: 0 0 0 0 !important;
        box-shadow: 0 0 0 0 !important;
    }

    .login_btn {
        width: 130px;
    }

        .login_btn:hover {
            color: #fff;
            background-color: #ff0000;
        }

    .btn-outline-danger {
        color: #fff;
        font-size: 18px;
        background-color: #28a745;
        background-image: none;
        border-color: #28a745;
    }

    .form-control {
        display: block;
        width: 100%;
        height: calc(2.25rem + 2px);
        padding: 0.375rem 0.75rem;
        font-size: 1.2rem;
        line-height: 1.6;
        color: #28a745;
        background-color: transparent;
        background-clip: padding-box;
        border: 1px solid #28a745;
        border-radius: 0;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .input-group-text {
        display: -ms-flexbox;
        display: flex;
        -ms-flex-align: center;
        align-items: center;
        padding: 0.375rem 0.75rem;
        margin-bottom: 0;
        font-size: 1.5rem;
        font-weight: 700;
        line-height: 1.6;
        color: #495057;
        text-align: center;
        white-space: nowrap;
        background-color: #e9ecef;
        border: 1px solid #ced4da;
        border-radius: 0;
    }
</style>

News/Views/News/Creat.cshtml
@model Newses

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


<html>
<head>
<title>New Event</title>
<link rel="stylesheet" href="css/style1.css">
</head>
<body>
<h2>New Text</h2>
<form method="post" style="border:3px solid #ccc" asp-controller="News" asp-action="Creat">
           <div class="container">
           <label asp-for="Id">Id</label>
                <input type="text" asp-for="Id">

           <label asp-for="Title">Tittle</label>
                <input type="text" asp-for="Title">

           <label asp-for="Text">Text</label>
                <input type="text" asp-for="Text">

                <input type="checkbox" checked="checked">Remember
           </div>
      <div class="clearfix">
<button type="cancel" class="btncan" asp-action="Index" asp-controller="Home">Cancel</button>
<button type="submit"class="btnsign">Send</button>

       </div>
</form>

</body>
<style>
    .container{
	padding:16px;
}
input[type=text],input[type=password]{
	width:100%;
	padding:12px 20px;
	margin:8px 0;
	display:inline-block;
	box-sizing:border-box;
	
}
button{
	background-color:#4caF50;
	color:white;
	padding:14px 20px;
	margin:8px 0;
	border:none;
	cursor:pointer;
	width:100%;
	
	
}
.btncan{
	padding:14px 20px;
	background-color:red;
}
.btncan,.btnsign{
	float:left;
	width:50%;
}
.clearfix::after{
	content:"";
	clear:both;
	display:table;
}
@Model screen and (max-width:300px){
	.btncan,.btnsign{
		width:100%;
	}
}
</style>
</html>

News/Views/News/Detail.cshtml
@model Reporter
<div class="border-3" style="text-align:left" >
       <div>
           <label class="form-label" asp-for="Id"></label>
           <input class="form-control" asp-for="Id" />
       </div>
    <div>
        <label class="form-label" asp-for="UserName"></label>
        <input class="form-control" asp-for="UserName" />
    </div>
    <div>
        <label class="form-label" asp-for="Age"></label>
        <input class="form-control" asp-for="Age" />
    </div>
    <a class="btn-success btn btn" asp-controller="Home" asp-action="Index">Back</a>
</div>

News/Views/News/Index.cshtml
@using News
@model List<Newses>
<h1>News
</h1><a class="btn-sm btn-dark" asp-controller="News" asp-action="Creat">New Event</a>
<table class="table table-striped table-hover table-dark  table-bordere w-100">
    <tr>
        <td>Id</td>
        <td>Tittle</td>
        <td>text</td>
        <td>Option</td>

    </tr>
    @foreach (var News in Model)
    {
        <tr>
            <td>@News.Id</td>
            <td>@News.Title.</td>
            <td>@News.Text</td>        
           <td> <form asp-controller="News" asp-action="Delete" asp-route-Id="@News.Id" method="post">
                <input type="submit" value="Delete" class="btn btn-danger"/>
            </form>            
            <form asp-controller="News" asp-action="Detail" asp-route-Id="@News.Id">
                <input type="submit" value="Detail" class="btn btn-success" />
                </form>          
            </td>
           </tr>
    }



</table>